# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"
